name: Fetch and Upload News Data

on:
  schedule:
    - cron: '0 * * * *'  # Esto ejecutará la acción cada hora

jobs:
  fetch_news_data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script to fetch news and upload to GitHub
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python main.py
