name: Subir Noticias a GitHub

on:
  schedule:
    - cron: '*/5 * * * *' 

jobs:
  upload-news:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script
        run: |
          python main.py
        env:
          NEWS_API_KEY: ${{ secrets.API_NEWS }}  # Usar el secreto correcto para el token de la API de noticias
          API_NEWS: ${{ secrets.GITHUB_TOKEN }}  # Asegúrate de pasar también el token de GitHub
