name: Fetch News and Save to JSON

on:
  schedule:
    # Ejecutar cada 5 minutos
    - cron: '*/5 * * * *'  # Esto es para ejecutar el trabajo cada 5 minutos
  workflow_dispatch:  # Esto permite ejecutar el flujo manualmente desde la interfaz de GitHub Actions

jobs:
  fetch_news_data:
    runs-on: ubuntu-latest  # Esto se ejecuta en un entorno Ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout del código de tu repositorio

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Puedes elegir la versión de Python que prefieras

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Instala las dependencias necesarias

      - name: Run the script to fetch news and save to JSON
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}  # Accede al secreto para la API Key
        run: |
          python main.py  # Ejecuta tu archivo principal para obtener noticias y guardarlas en JSON
